application:
  host:
  port:
  read_timeout:
  write_rtimeout:

mysql:
  Addr:
  UserName:
  Password:
  ShowLog:                    # 是否打印所有SQL日志
  MaxIdleConn:                  # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn:                  # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime:              # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些
  SlowThreshold:              # 慢查询阈值，设置后只打印慢查询日志，默认为500ms

redis:
  Addr:
  Password: ""
  DB:
  MinIdleConn:
  DialTimeout:
  ReadTimeout:
  WriteTimeout:
  PoolSize:
  PoolTimeout:
  IsTrace:

auth:
  jwt_secret: